config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'welcome/index'
  root 'welcome#index'

  get "sign_up" => "users#sign_up", :as => "sign_up"
  #resource :users, only: [:create]

  resources :users do
    collection do
      get 'sign_up'
    end
  end

  resources :posts do
     collection do
       get :posts_in_2017
       get :posts_in_2016
       get :posts_in_2015
       get :posts_in_2014
     end
  end


end

app/models/ckeditor/asset.rb
class Ckeditor::Asset
  include Ckeditor::Orm::Mongoid::AssetBase

  delegate :url, :current_path, :size, :content_type, :filename, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/kindeditor/asset.rb
class Kindeditor::Asset < ActiveRecord::Base
  self.table_name = 'kindeditor_assets'
  mount_uploader :asset, Kindeditor::AssetUploader
  validates_presence_of :asset
  before_save :update_asset_attributes
  
  private
  def update_asset_attributes
    if asset.present? && asset_changed?
      self.file_size = asset.file.size
      self.file_type = asset.file.content_type
    end
  end
end

app/models/kindeditor/file.rb
class Kindeditor::File < Kindeditor::Asset
  mount_uploader :asset, Kindeditor::FileUploader
end

app/models/kindeditor/flash.rb
class Kindeditor::Flash < Kindeditor::Asset
  mount_uploader :asset, Kindeditor::FlashUploader
end

app/models/kindeditor/image.rb
class Kindeditor::Image < Kindeditor::Asset
  mount_uploader :asset, Kindeditor::ImageUploader
end

app/models/kindeditor/media.rb
class Kindeditor::Media < Kindeditor::Asset
  mount_uploader :asset, Kindeditor::MediaUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  scope :created_in, ->(year) { where( "YEAR( created_at ) = ?", year ) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #简单加密一下，防止被人篡改
  http_basic_authenticate_with name: "821222837@qq.com", password: "huhaiyang361010", except: [:index, :show ,:posts_in_2017 ,:posts_in_2016 ,:posts_in_2015 ,:posts_in_2014 ]

  layout 'posts_index'

  def index
    #@posts = Post.order('updated_at DESC')
    @posts = Post.order('updated_at DESC').page(params[:page]).per(10)
  end

  def posts_in_2017
    @posts = Post.created_in(2017).order('updated_at DESC').page(params[:page]).per(10)
  end

  def posts_in_2016
    @posts = Post.created_in(2016).order('updated_at DESC').page(params[:page]).per(10)
  end

  def posts_in_2015
    @posts = Post.created_in(2015).order('updated_at DESC').page(params[:page]).per(10)
  end

  def posts_in_2014
    @posts = Post.created_in(2014).order('updated_at DESC').page(params[:page]).per(10)
  end
  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "The article has been successfully created."
    else
      render 'new'
    end
  end

  def show
    @post= Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def last_post
    @post = Post.last
  end


  private
  def post_params
    params.require(:post).permit(:title,:content)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def last_post
    @post  = Post.last
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Gavin</title>


  <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css'>

  <%= stylesheet_link_tag "application", :media => "all" %>

</head>

<body>

    <div class="site-wrapper" >
      <div class="site-wrapper-inner">

        <div class="container">

          <div class="masthead clearfix">
            <div class="container inner">
              <h3 class="masthead-brand">HaiyangHu</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">首页</a></li>
                  <li><%= link_to "文章",'/posts'%></li>

                  <li><a href="#">其他</a></li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="inner cover">
            <h1 class="cover-heading">HHY</h1>
            <p class="lead">RUN MORE , DO MORE</p>
            <p class="lead">

            </p>
          </div>

        </div>

      </div>

    </div>
</body>
</html>



app/views/layouts/posts_index.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "post_layout_require" %>
    <%= javascript_include_tag "application" %>
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>关于技术</title>

    <!-- Bootstrap core CSS -->
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
              <div class="container-fluid">
                          <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                              <span class="sr-only">Toggle navigation</span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="/">Haiyang Hu</a>
                          </div>
                          <div id="navbar" class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                              <li class="active"><a href="/">Home</a></li>
                              <li><a href="#">About</a></li>
                              <li><a href="#">Contact</a></li>
                            </ul>
                          </div><!--/.nav-collapse -->
                        </div><!--/.container-fluid -->
                        </nav>

      <div class="blog-header">
        <h1 class="blog-title">一些笔记而已</h1>
        <p class="lead blog-description">字写得不好，所以就用键盘来记录生活和工作的一些事情.</p>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
          <%= yield%>


        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>关于</h4>
            <p>生活除了code和bug还有睡觉和睡觉</p>
          </div>
          <div class="sidebar-module">
            <h4>归档</h4>
            <ol class="list-unstyled">
              <li><%= link_to '2017文章', :action => :posts_in_2017 %></li>
              <li><%= link_to '2016文章', :action => :posts_in_2016 %></li>
              <li><%= link_to '2015文章', :action => :posts_in_2015 %></li>
              <li><%= link_to '2014文章', :action => :posts_in_2014 %></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>其他</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/layouts/sign_layout.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <title>Haiyang Hu</title>
     <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">管理后台</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "注册", sign_up_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
    </nav>

          <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
  <%= form_for @post  do |f| %>
    <p>
    <%= f.label :文章标题 %>
    <%= f.text_field :title %>
    </p>
    <p>
    <%#= f.label :文章内容 %>
    <%#= f.cktext_area :content %>

    <%= f.kindeditor :content %>
    </p>

    <p>
    <%= f.submit '提交', class: 'btn btn-primary' %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<h1>修改文章</h1>

<%= render 'form'%>

<%= link_to '返回列表', posts_path%>

app/views/posts/index.html.erb
<div class="blog-post">
<%= paginate @posts %>
  <% @posts.each do |post| %>
    <div class="panel panel-default">
    <div class="panel-body">
      <h2 class="blog-post-title" ><%= post.title%></h2>
      <p class="blog-post-meta"><%= post.created_at.strftime("%Y-%m-%d %H:%M:%S")%> by <a href="#">Gavin</a></p>
      <%#<p><%= truncate(post.content,:length=>330).gsub(/<.*?>/,'') %></p>
      <% content = post.content[0,150] %>
      <p><%= sanitize content %></p>
      <%= link_to '查看', post_path(post)  , class: 'btn btn-default' %>
      </div>
    </div>
  <%end%>
<%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1>新建文章</h1>

<%= render 'form'%>

<%= link_to '返回列表',posts_path %>

app/views/posts/posts_in_2014.html.erb
<div class="blog-post">
<%= paginate @posts %>
  <% @posts.each do |post| %>
    <div class="panel panel-default">
    <div class="panel-body">
      <h2 class="blog-post-title" ><%= post.title%></h2>
      <p class="blog-post-meta"><%= post.created_at.strftime("%Y-%m-%d %H:%M:%S")%> by <a href="#">Gavin</a></p>
      <%#<p><%= truncate(post.content,:length=>330).gsub(/<.*?>/,'') %></p>
      <% content = post.content[0,150] %>
      <p><%= sanitize content %></p>
      <%= link_to '查看', post_path(post)  , class: 'btn btn-default' %>
      </div>
    </div>
  <%end%>
<%= paginate @posts %>
</div>

app/views/posts/posts_in_2015.html.erb
<div class="blog-post">
<%= paginate @posts %>
  <% @posts.each do |post| %>
    <div class="panel panel-default">
    <div class="panel-body">
      <h2 class="blog-post-title" ><%= post.title%></h2>
      <p class="blog-post-meta"><%= post.created_at.strftime("%Y-%m-%d %H:%M:%S")%> by <a href="#">Gavin</a></p>
      <%#<p><%= truncate(post.content,:length=>330).gsub(/<.*?>/,'') %></p>
      <% content = post.content[0,150] %>
      <p><%= sanitize content %></p>
      <%= link_to '查看', post_path(post)  , class: 'btn btn-default' %>
      </div>
    </div>
  <%end%>
<%= paginate @posts %>
</div>

app/views/posts/posts_in_2016.html.erb
<div class="blog-post">
<%= paginate @posts %>
  <% @posts.each do |post| %>
    <div class="panel panel-default">
    <div class="panel-body">
      <h2 class="blog-post-title" ><%= post.title%></h2>
      <p class="blog-post-meta"><%= post.created_at.strftime("%Y-%m-%d %H:%M:%S")%> by <a href="#">Gavin</a></p>
      <%#<p><%= truncate(post.content,:length=>330).gsub(/<.*?>/,'') %></p>
      <% content = post.content[0,150] %>
      <p><%= sanitize content %></p>
      <%= link_to '查看', post_path(post)  , class: 'btn btn-default' %>
      </div>
    </div>
  <%end%>
<%= paginate @posts %>
</div>

app/views/posts/posts_in_2017.html.erb
<div class="blog-post">
<%= paginate @posts %>
  <% @posts.each do |post| %>
    <div class="panel panel-default">
    <div class="panel-body">
      <h2 class="blog-post-title" ><%= post.title%></h2>
      <p class="blog-post-meta"><%= post.created_at.strftime("%Y-%m-%d %H:%M:%S")%> by <a href="#">Gavin</a></p>
      <%#<p><%= truncate(post.content,:length=>330).gsub(/<.*?>/,'') %></p>
      <% content = post.content[0,150] %>
      <p><%= sanitize content %></p>
      <%= link_to '查看', post_path(post)  , class: 'btn btn-default' %>
      </div>
    </div>
  <%end%>
<%= paginate @posts %>
</div>

app/views/posts/show.html.erb
<div class="blog-post">
  <div class="panel panel-default">
    <div class="panel-body">
      <h2 class="blog-post-title" ><%= @post.title%></h2>
      <p class="blog-post-meta"><%= @post.created_at.strftime("%Y-%m-%d %H:%M:%S")%> by <a href="#">Gavin</a></p>

      <p><%#= sanitize @post.content %></p>
      <p><%= raw @post.content %></p>
      <%= link_to '返回列表' , controller: 'posts', class:'btn btn-default' %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1 align="center" ></h1>